# Generated by Django 5.2.1 on 2025-05-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_rename_certificatntaionalite_inscription_certificatnationalite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='numero_inscription',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
